export const CONST = {
  SET_COORDS: 'SET_COORDS',
  SET_LOCATION_NAME: 'SET_LOCATION_NAME',
  SET_FOUND_LOCATIONS: 'SET_FOUND_LOCATIONS',
  SET_MAP_DATA: 'SET_MAP_DATA',
  SET_CURRENT_WEATHER_DATA: 'SET_CURRENT_WEATHER_DATA',
};
